### ISSUE TITLE
Api Deal Products Breaking Changes

### ISSUE THREAD

**Issue by Sprudhomme** [DavidRouyer/pipedrive-dotnet#107]
**Describe the bug**
Pipedrive api changed to update PUT prices to be sent as an array of objects instead of an object : https://developers.pipedrive.com/changelog/post/breaking-change-in-products-endpoint-and-webhook

Also breaking GetProducts from deal since it was using the same model

Created a PR with a fix
I am running from my updated dll at the moment.

**To Reproduce**
1. Fetch deal products

**Expected behavior**
Return products of Deal

**Screenshots**
Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'System.Collections.Generic.Dictionary`2[System.String,Pipedrive.ProductPrice]' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly
Path 'data[0].product.prices', line 1, position 939.

**Comment by DavidRouyer** [comment]
Fixed in fada60ebbee79ae93aa16403dcf2eec7e468fd9d

**Comment by DavidRouyer** [comment]
Tell me if it's good in `0.5.18`

**Comment by Sprudhomme** [comment]
Yes! Working as intended in 0.5.18
