### ISSUE TITLE
New to Pipe drive (Help Wanted!)

### ISSUE THREAD

**Issue by gokul-prasadh** [DavidRouyer/pipedrive-dotnet#112]
Hi,
I am totally new to the API works, my scenario is In my project we're planned to integrate the pipe drive data into the local database. I have searched many things regards that, I couldn't find out anything except your code. I need your help to how to do it or how can I use your code to learn . please let me know your thoughts.

**Comment by dombarnes** [comment]
You need to give more info. What aspects are you integrating. Do you want to sync info to your DB and sync changes back up?
Your question is a bit too general.
