### ISSUE TITLE
Subscription.GetByDealId trows NullReferenceException if the Subscription not Exist

### ISSUE THREAD

**Issue by SergeBerwert** [DavidRouyer/pipedrive-dotnet#113]
When I call GetByDealId the library throws NullReferenceException if there is no Subscription

`var res = await client.Subscription.GetByDealId(65);`

The HttpRespons code is No content. 

```
public async Task<T> Get<T>(Uri uri, IDictionary<string, string> parameters)
{
    Ensure.ArgumentNotNull(uri, nameof(uri));

    var response = await Connection.Get<JsonResponse<T>>(uri, parameters, null).ConfigureAwait(false);
    return response.Body.Data;
}
```

Body is in this case null which causes the error when it trys to access .Data

**Comment by DavidRouyer** [comment]
I'm introducing a `NoContentException`, so you can do:

```csharp
var pipedrive = Helper.GetAuthenticatedClient();

try {
  var subscription = await pipedrive.Subscription.GetByDealId(540);
} catch (NoContentException e) {
  // No subscription on deal
}
```

**Comment by DavidRouyer** [comment]
Pipedrive.net v0.5.19 has been released https://github.com/DavidRouyer/pipedrive-dotnet/releases/tag/v0.5.19
