### ISSUE TITLE
`TimeRange` CustomField isn't parsed properly

### ISSUE THREAD

**Issue by k-visscher** [DavidRouyer/pipedrive-dotnet#123]
**Describe the bug**
When handling a PipeDrive response with a `TimeRange` Custom Field.
The function `CustomFieldConverter.ReadJson()` throws an exception since it tries to parse an time span represented as an string as an integer.

**To Reproduce**
1. Add a custom TimeRange field to your deal.
2. Create a deal.
3. Mutate/edit/update the deal using `PipedriveApiClient.Deal.Edit()`, while making sure to set the custom TimeRange field you just created.
4. Wait for the response to be recieved/parsed.
5. Error while deserializing.

**Expected behavior**
I expected `pipedrive-dotnet` to parse this as an timespan not an integer.

**Screenshots**
<img width="522" alt="image" src="https://user-images.githubusercontent.com/13816979/179942995-9cca73e1-6b69-4995-8bfb-ddf7535d4f63.png">
<img width="559" alt="image" src="https://user-images.githubusercontent.com/13816979/179943688-f37d2c8a-834c-4abf-b61f-f37b12058262.png">

**Version Info**
`0.5.18` from NuGet.

**Comment by DavidRouyer** [comment]
Thank you for your bug report, it looks like the `timezone_id` isn't an int anymore

**Comment by DavidRouyer** [comment]
Pipedrive.net v0.5.19 has been released https://github.com/DavidRouyer/pipedrive-dotnet/releases/tag/v0.5.19

**Comment by k-visscher** [comment]
> Pipedrive.net v0.5.19 has been released https://github.com/DavidRouyer/pipedrive-dotnet/releases/tag/v0.5.19

tyvm!
