### ISSUE TITLE
DealChange

### ISSUE THREAD

**Issue by lamazze** [DavidRouyer/pipedrive-dotnet#132]
Hello,

I'm trying to list all the Stage update for a Deal.

I'm using Deal.GetUpdates(<deal>, <options>) for that.

My problem is that when Object == "dealChange", I have no idea how to get the corresponding values.
The "Data" property is of type IDealUpdateEntity which has only one member "Id".
There is a DealChange class in the code which is obviously the right class for "dealChange" but I don't understand how to convert it (if it's only possible).

Sorry if I'm missing the obvious.

Thank you!
lamaZZe

**Comment by lamazze** [comment]
Ignore me sorry. You just have to typecast Data. I would delete my question if I could.

**Comment by DavidRouyer** [comment]
If you need some documentation you can look at the tests :)
