### ISSUE TITLE
ActivityField ID can be null

### ISSUE THREAD

**Issue by NChampion** [DavidRouyer/pipedrive-dotnet#14]
get /activitityFields can return null for addresses at least in my case and thus can't be serialized/de-serialized with JSON.

https://developers.pipedrive.com/docs/api/v1/#!/ActivityFields

Example:
{

    "id": null,
    "key": "location_country",
    "name": "Country",
    "field_type": "varchar",
    "edit_flag": false,
    "active_flag": true,
    "is_subfield": true,
    "mandatory_flag": true
}

**Comment by DavidRouyer** [comment]
Thanks, see v0.0.31 for the fix

**Comment by NChampion** [comment]
Awesome, thank you!
