### ISSUE TITLE
How to update a custom field of an entity?

### ISSUE THREAD

**Issue by adrianNegrusa** [DavidRouyer/pipedrive-dotnet#27]
Hi,
I think from here is the problem (this line; i don't have returned an customfield with length 40):
https://github.com/DavidRouyer/pipedrive-dotnet/blob/c86f20abad76dd5dd72c130fd45aca38e46ea561/src/Pipedrive.net/Converters/CustomFieldConverter.cs#L26

I need to update the person fields: like address
I will show what i have returned(the json object, see below "postal_address" and all fields):
 
{
  "success": true,
  "data": {
    "id": 7517,
    "company_id": 333,
    "owner_id": {
      "id": 9055552398,
      "name": "888",
      "email": "888",
      "has_pic": false,
      "pic_hash": null,
      "active_flag": true,
      "value": 888
    },
    "org_id": null,
    "name": "gmail.com",
    "first_name": "gmail.com",
    "last_name": "",
    "open_deals_count": 0,
    "related_open_deals_count": 0,
    "closed_deals_count": 0,
    "related_closed_deals_count": 0,
    "participant_open_deals_count": 0,
    "participant_closed_deals_count": 0,
    "email_messages_count": 3,
    "activities_count": 0,
    "done_activities_count": 0,
    "undone_activities_count": 0,
    "reference_activities_count": 0,
    "files_count": 0,
    "notes_count": 1,
    "followers_count": 1,
    "won_deals_count": 0,
    "related_won_deals_count": 0,
    "lost_deals_count": 0,
    "related_lost_deals_count": 0,
    "active_flag": true,
    "phone": [
      {
        "label": "",
        "value": "121312312321",
        "primary": true
      }
    ],
    "email": [
      {
        "label": "",
        "value": "xxxgmail.com",
        "primary": true
      }
    ],
    "first_char": "m",
    "update_time": "2019-10-03 07:01:24",
    "add_time": "2019-10-01 09:10:26",
    "visible_to": "7",
    "picture_id": null,
    "next_activity_date": null,
    "next_activity_time": null,
    "next_activity_id": null,
    "last_activity_id": null,
    "last_activity_date": null,
    "last_incoming_mail_time": "2019-10-03 07:01:00",
    "last_outgoing_mail_time": "2019-10-02 17:57:00",
    "ef81aec5402268d5860c8dbfd2704c167a637e17": null,
    "b485548aa0d5509a066eed2449a78f409977d3cd": null,
    "9a8bd76c75787157d973303cbe68a1afe47a8cf6": null,
    "ea9b9368d874845341b252eaaf75dac16b2a5b7e": null,
    "b22b376a77834be3bde1d69565d9248779126a8d": null,
    "131ea976ce5d4f2a9b2f698d3c67d4b3f4acbcf1": null,
    "label": null,
    "5193fc51b56f8b1845aafccf34d994cf6042b7d4": null,
    "im": [
      {
        "value": "",
        "primary": true
      }
    ],
    "postal_address": "157 Adelaide St W,Toronto,CA",
    "postal_address_subpremise": null,
    "postal_address_street_number": "157",
    "postal_address_route": "Adelaide Street West",
    "postal_address_sublocality": "Old Toronto",
    "postal_address_locality": "Toronto",
    "postal_address_admin_area_level_1": "Ontario",
    "postal_address_admin_area_level_2": "Toronto Division",
    "postal_address_country": "Canada",
    "postal_address_postal_code": "M5H 1P9",
    "postal_address_formatted_address": "157 Adelaide St W, Toronto, ON M5H 1P9, Canada",
    "notes": null,
    "birthday": "2019-09-20",
    "job_title": null,
    "0d207ccc37bc39a39bd8583ae59c8a9de34ddabd": null,
    "e366acb4568cd4709050930608a33d0f51caae03": null,
    "584c954714f3dcc48400b945843bfc7ee962f2a2": null,
    "c728280ba88a3a90461387daf47b4cf38d7327ba": null,
    "org_name": null,
    "cc_email": "2shipsolutions@pipedrivemail.com",
    "owner_name": "xxx"
  },
  "additional_data": {
    "dropbox_email": "2shipsolutions@pipedrivemail.com"
  },
  "related_objects": {
    "user": {
      "9052398": {
        "id": 9052398,
        "name": "Patricia Whitney",
        "email": "xxx",
        "has_pic": false,
        "pic_hash": null,
        "active_flag": true
      }
    }
  }
}

**Comment by DavidRouyer** [comment]
Each `entity.Edit` method taks a `EntityUpdate` as argument.
You can pass a [`Dictionary<string, ICustomField> CustomFields`](https://github.com/DavidRouyer/pipedrive-dotnet/blob/af87663c5346b788c4ffd65c21e6641c420509cc/src/Pipedrive.net/Models/Request/PersonUpdate.cs#L29) to an `EntityUpdate` class.

If you want to update an address, use the [`AddressCustomField`](https://github.com/DavidRouyer/pipedrive-dotnet/blob/master/src/Pipedrive.net/Models/Common/CustomFields/AddressCustomField.cs).
