### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by mesuttascic** [DavidRouyer/pipedrive-dotnet#29]
Hi David,
I'm stuck on file upload. I activated your "Task<File> Create(NewFile data)" function. I worked on it but didn't achieve.

**Comment by MRVDH** [comment]
Here is an example of how I did it.
createdDeal is the response object of the deal that I just created via this API.

```C#
    using var multipartFormDataContent = new MultipartFormDataContent();

    using var dealIdStringContent = new StringContent(createdDeal.Id.ToString());
    multipartFormDataContent.Add(dealIdStringContent, "deal_id");
    using var fileByteArrayContent = new ByteArrayContent(_pdfFile);
    fileByteArrayContent.Headers.ContentType = new MediaTypeHeaderValue("application/pdf");
    multipartFormDataContent.Add(fileByteArrayContent, "file", "file.pdf");

    using var httpClient = new HttpClient();
    var response = await httpClient.PostAsync(new Uri($"{endpoint}v1/files?api_token={ token }"), multipartFormDataContent);
```

**Comment by DavidRouyer** [comment]
I never made it work, I'll try again soon with a ByteArray instead of a stream like @MRVDH did

**Comment by DavidRouyer** [comment]
You can upload a file with the API now

**Comment by mesuttascic** [comment]
Thanks a lot,
I had solved with restsharp.
As soon as possible i will change and use that codeblock.

**Comment by DavidRouyer** [comment]
You can do `client.Files.Create(yourFile)` now https://github.com/DavidRouyer/pipedrive-dotnet/blob/dcdb1f559ff632997d804deac13361cc28826e09/src/Pipedrive.net/Clients/FilesClient.cs#L43
