### ISSUE TITLE
OAuth integration

### ISSUE THREAD

**Issue by geasi** [DavidRouyer/pipedrive-dotnet#3]
As of PipeDrive's docs, they support OAuth:
https://pipedrive.readme.io/docs/marketplace-oauth-authorization

The library is already compatible with OAuth? 
If not, do you have plans to make it? 
If yes, how can we use the library with OAuth?

**Comment by DavidRouyer** [comment]
This library isn't actually compatible with OAuth because the goal was to implement a client for the [stateless API](https://developers.pipedrive.com/docs/api/v1/#/), but PRs are welcome!

**Comment by geasi** [comment]
Ok @DavidRouyer !
I already made a fork of your repository and started to work on that. The first commit I made in my repository worked, but the code I far away from where I would like to go. I will make many refactoring in my newly created code, so do not panic if you take a look at it! hahaha
I totally agree with the stateless approach and I will follow this approach.

Thank's!

**Comment by geasi** [comment]
Hi @DavidRouyer !

I just created the pull request for the OAuth support.
Could you take a look, please?
https://github.com/geasi/pipedrive-dotnet/pull/1

Thanks!

**Comment by geasi** [comment]
Hi @DavidRouyer ,
Did you have some time to take a look at it?

Thanks!

**Comment by DavidRouyer** [comment]
@geasi Of course! I'll take a look this week-end

**Comment by geasi** [comment]
@DavidRouyer thank you, I appreciate!

**Comment by DavidRouyer** [comment]
I've started to work on it, see #4

**Comment by DavidRouyer** [comment]
@geasi I've implemented everything, please test it and if you need guidance to use it please tell me.
I'll add a section in the README

**Comment by geasi** [comment]
@DavidRouyer ok!
Sorry for the delay, I could not take a look at it before.
I am going to update my local repository and start testing today.
I have a question: I need to update the company's and person's custom fields. I found that the NewOrganization and NewPerson classes both have a custom field property, but not PersonUpdate nor OrganizationUpdate. What do you think that would be more appropriate: implement it in the same PR or in a new one?

Thank a lot!

**Comment by DavidRouyer** [comment]
@geasi Make as little changes as possible when you create a PR and focus on one thing.
You don't need to update your repository, you can clone mine and use the `authentication` branch

**Comment by geasi** [comment]
Ok @DavidRouyer!

**Comment by geasi** [comment]
Hi @DavidRouyer 

I added some missing parameters to OAuthTokenRequest class, for example, but I could no push it to authentication branch. Can you kindly give permission to me, please?
I also added a method on OAuthClient class to refresh the user token.

I think the only problem I had was deserializing the OAuthToken response for the authorization code flow. Although I added JsonProperty attributes on the OAuthToken class, the method JsonHttpPipeline.DeserializeResponse expects a response format like that:

`{
  "success": true,
  "data": { 
    "access_token": "...",
    "refresh_token": "...",
    "expires_in": "...",
    "scope": "..."
  },
  "additional_data": {},
  "related_objects": {}
}`

But for the token response we get this:

`{ 
    "access_token": "...",
    "refresh_token": "...",
    "expires_in": "...",
    "scope": "..."
}`

**Comment by DavidRouyer** [comment]
Actually, I followed the docs: https://pipedrive.readme.io/docs/marketplace-oauth-authorization
If you have issues it means the docs are wrong :/

Can you tell me what parameters are missing on `OAuthTokenRequest`? I'll add them
I'll fix the response for `OAuthToken` tonight

I have to test it myself but the process for creating an app is quite painful :/

**Comment by geasi** [comment]
@DavidRouyer 
Please, just add the permission to push to the authorization branch, it is going to be easier, ok?
So you can review my code.

**Comment by DavidRouyer** [comment]
You don't need any permission to push on my branch. I won't allow anyone to push code directly so use the standard GitHub workflow. 
You just have to create a pull request against the right branch so I can review it.

**Comment by geasi** [comment]
Ahh ok, sorry.

I will make it.

Em sex, 12 de abr de 2019 às 17:40, David Rouyer <notifications@github.com>
escreveu:

**Comment by geasi** [comment]
@DavidRouyer 

Sorry for the delay but I just made the commits I told you. Also created the pr.
I made a little refactoring in the authorization code flow and also added the refresh token flow, as the access token is valid for 1 hour only.
In my test, these changes are working with Pipedrive but with a workaround: the JsonHttpPipeline class is not able to deserialize the token's response (both access token and refresh token flows) as the response does not have the same body as the JsonResponse<T> class does. I added the code above just to make my local version work:

`var json = JsonConvert.DeserializeObject<JsonResponse<T>>(body);

if (json.Data == null)
	newBody = JsonConvert.DeserializeObject<T>(body);
else
	newBody = json.Data;`

I completely agree that this workaround would not be the final solution and this is why I did not added this change to the pr. I will try to figure out a final solution soon.

**Comment by geasi** [comment]
Another important point, in the project I'm developing I need to get the current user domain.
For this, they provide a method (users/me) and three properties in the response to provide this information.
I just added this commit also, ok?

**Comment by geasi** [comment]
@DavidRouyer,

I just added the revoke token flow as in their documentation: https://pipedrive.readme.io/docs/app-uninstallation#section-token-revocation
In all my tests the code is working correctly, but still with that "hotfix" in the JsonHttpPipeline class.
I appreciate if you have some time to kindly review it.

Thanks!

**Comment by DavidRouyer** [comment]
I'll make some changes to the `JsonHttpPipeline` by putting the `JsonResponse` in the `ApiResponse` class, but it's not a trivial change. It's the best solution I've found to handle both JSON responses

**Comment by geasi** [comment]
Ok, thanks!

**Comment by DavidRouyer** [comment]
@geasi #4 is ready to be merged, can you test it?
