### ISSUE TITLE
Error on create/update person, Activity or Deal objects

### ISSUE THREAD

**Issue by satyat110** [DavidRouyer/pipedrive-dotnet#35]
Hi,

I am facing the Api call issue while create/update person, Activity or deal. Error message - “Internal Server Error occurred. Pipedrive staff was notified about this.”.
It was working fine a day ago and updated the latest version with pipedrive.net as well.

Really appreciate your help.

Thanks,
Satya

**Comment by DavidRouyer** [comment]
Hi, this was fixed in 0.1.9
