### ISSUE TITLE
Exception in retrieving the Person fields

### ISSUE THREAD

**Issue by sumiyafaruq** [DavidRouyer/pipedrive-dotnet#41]
Hi David,

`await pipedriveClient.PersonField.GetAll();` was working fine earlier. But today while I was trying to read the person fields of a new pipedrive sandbox, I see that it is throwing the below exception:

Could not convert string to DateTime: 0000-00-00 00:00:00. Path 'data[4].add_time', line 1, position 1950.

Really appreciate your help.

**Comment by DavidRouyer** [comment]
Hi,

Have you created a person field with an empty `add_time`?
`add_time` is non nullable as https://github.com/DavidRouyer/pipedrive-dotnet/blob/6f4c4e1691b1c98e4e75a3304f554f74d973aff0/src/Pipedrive.net/Models/Response/PersonField.cs#L22

**Comment by mvakulich** [comment]
Hi, sometimes Pipidrive set  DateTime: 0000-00-00 00:00:00 to some default fields
I've experienced same problem last days

**Comment by DavidRouyer** [comment]
Please report this to Pipedrive, it's a bug on their end. `add_time` should always been set to the date you've created the field. I saw similar discussions on other dates https://devcommunity.pipedrive.com/t/first-won-time-in-the-deal-is-0000-00-00-0000/2350

**Comment by DavidRouyer** [comment]
Does it still occurs?

**Comment by DavidRouyer** [comment]
Closed due to inactivity
