### ISSUE TITLE
Specific BaseAddress

### ISSUE THREAD

**Issue by MRVDH** [DavidRouyer/pipedrive-dotnet#43]
From the example in the readme file it looks like this library requires a 'company.pipedrive.com' base address. However, if I set up my own http client I can just make calls to `https://api.pipedrive.com/v1/persons?api_token=<token>` with the specific token for an organization in place.

Is there a different constructor where I don't need to set a 'company.pipedrive.com' base address?

**Comment by DavidRouyer** [comment]
There is no constructor that doesn't require the company domain name because I only follow the official Pipedrive documentation https://pipedrive.readme.io/docs/core-api-concepts-about-pipedrive-api

**Comment by MRVDH** [comment]
There as well requests are being sent like this. If you enter an api key and execute one of the requests then check the network it looks like this:
![image](https://user-images.githubusercontent.com/6686385/77207397-8ccf0580-6af9-11ea-9e72-08bdef10abc8.png)

The reference you posted does mention the company domain name, but that doesn't actually seem to be needed. I will do some further testing with this to find out why they actually recommend it.

**Comment by MRVDH** [comment]
Closing this for now since I'm just gonna do it with the base address
