### ISSUE TITLE
Support for "Add a follower to a person"

### ISSUE THREAD

**Issue by MRVDH** [DavidRouyer/pipedrive-dotnet#44]
Hi, I see that there is no support for the "Add a follower to a person" method. Is this planned?
https://developers.pipedrive.com/docs/api/v1/#!/Persons/post_persons_id_followers

**Comment by MRVDH** [comment]
I see that there is support for adding a follower to a deal, so maybe it's just a simple code copy paste and changing deal to person?

**Comment by DavidRouyer** [comment]
Get/Add/Delete followers endpoints have been added for Persons/Organizations
