### ISSUE TITLE
Change 'IntCustomField' to 'LongCustomField'

### ISSUE THREAD

**Issue by robertmaidlaAW** [DavidRouyer/pipedrive-dotnet#48]
Numerical int custom fields should be updated to long custom fields as int greatly restricts the API usage.

I noticed that a corresponding [Pull Request](https://github.com/DavidRouyer/pipedrive-dotnet/pull/21) has already been submitted. I also added a few comments that helped get the logic working for me locally.

**Comment by sumiyafaruq** [comment]
Hi @DavidRouyer Any ETA when this will be available in the release?

**Comment by DavidRouyer** [comment]
Fixed in 2c50bfd9ac39f9721664415cfa8eb27c81c575ca

**Comment by DavidRouyer** [comment]
0.4.0 has been published
