### ISSUE TITLE
expected_close_date missing

### ISSUE THREAD

**Issue by GreggDeB** [DavidRouyer/pipedrive-dotnet#59]
expected_close_date needs to be added to both newdeal and dealupdate.

**Comment by gregarican** [comment]
This is present in one file within my pull request. See https://github.com/DavidRouyer/pipedrive-dotnet/blob/fd5f26cd7d7d704805e6c978cbbae55bb2f9e7dc/src/Pipedrive.net/Models/Request/NewDeal.cs.

**Comment by DavidRouyer** [comment]
Fixed in 210aced927d22733cdedfb740697c4f67f8e0bf3 and d651230d43703eb88f9a49c1afc429941cebe83c

**Comment by DavidRouyer** [comment]
Pipedrive.net v0.5.3 has been released https://github.com/DavidRouyer/pipedrive-dotnet/releases/tag/v0.5.3
