### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by geasi** [DavidRouyer/pipedrive-dotnet#6]
Hi @DavidRouyer,

As described in the following link, Pipedrive has a rate-limiting implemented to their API:
https://pipedrive.readme.io/docs/core-api-concepts-rate-limiting

I tested this scenario calling their API and the result is that, after I reach the two-seconds interval limit, the client throws a TooManyRequestsException. Ok, this makes sense. 
Although, we have another class (RateLimitExceededException), with properties like Limit, Reset and Remaining that would help a lot to set wait times in my application.
The question is: am I misusing the client and, because of that, I am not able to get to the RateLimitExceededException? Or is it only a misunderstanding by myself?

Their page explains that, if we reach the rate limit, the API is going to send a 429 response code.
If I am not wrong, the code does not exactly follow this:

```csharp
static readonly Dictionary<HttpStatusCode, Func<IResponse, Exception>> _httpExceptionMap =
	new Dictionary<HttpStatusCode, Func<IResponse, Exception>>
	{
		{ HttpStatusCode.Unauthorized, GetExceptionForUnauthorized },
		{ HttpStatusCode.Forbidden, GetExceptionForForbidden },
		{ HttpStatusCode.NotFound, response => new NotFoundException(response) },
		{ (HttpStatusCode)422, response => new ApiValidationException(response) },
		{ (HttpStatusCode)429, response => new TooManyRequestsException(response) },
		{ HttpStatusCode.InternalServerError, response => new InternalServerErrorException(response) },
		{ HttpStatusCode.NotImplemented, response => new NotImplementedException(response) }
	};


static Exception GetExceptionForForbidden(IResponse response)
{
	string body = response.Body as string ?? "";

	if (body.Contains("rate limit exceeded"))
	{
		return new RateLimitExceededException(response);
	}

	if (body.Contains("number of login attempts exceeded"))
	{
		return new LoginAttemptsExceededException(response);
	}

	if (body.Contains("abuse-rate-limits") || body.Contains("abuse detection mechanism"))
	{
		return new AbuseException(response);
	}

	return new ForbiddenException(response);
}
```

From the above pieces of code, we can see that we are only going to get a RateLimitException if the response is Forbidden (403), right?

I think that I understood what happened: although they state this: 

> If you exceed the rate limit, our API will start rejecting your requests and you'll receive an error response of HTTP 429 "Too Many Requests" in the **body**:

... they also send the HTTP 429 status as the code for the response. So the 429 status code could be read from the body AND the response code. Practically, I do not think this makes sense to send the response code in the body if it is the same code from the response, but this is what happened in my tests.

I appreciate if you can review this issue and confirm if I am making some mistake here.

Kind regards,
Geasi Puozzo

**Comment by DavidRouyer** [comment]
Currently, my integration tests are failing because of the rate limiting, you can take a look at the logs on Travis: https://travis-ci.org/DavidRouyer/pipedrive-dotnet/jobs/521726150 and they are failing with the right exception `Pipedrive.TooManyRequestsException : request over limit` so it should work as expected.
You can take a look at the Octokit documentation https://octokitnet.readthedocs.io/en/latest/getting-started/#too-much-of-a-good-thing-dealing-with-api-rate-limits, `GetLastApiInfo()` is implemented but I haven't tried it myself yet

**Comment by geasi** [comment]
Good stuff @DavidRouyer 
I will make some tests with the GetLastApiInfo method and let you know as soon as finish it.
Thanks!
