### ISSUE TITLE
pipedrive.Person.GetByEmail(EmailAddress) missing

### ISSUE THREAD

**Issue by Luvnet-890** [DavidRouyer/pipedrive-dotnet#66]
Hi, We use to have pipedrive.Person.GetByEmail(EmailAddress) at person object in 0.4.0 version and now its missing. Can you please help us in achieving this EmailAddress based search in the latest version.

**Comment by DavidRouyer** [comment]
Hi, `Find` endpoints have been replaced by `Search` endpoints, see https://github.com/DavidRouyer/pipedrive-dotnet/releases/tag/v0.5.0

**Comment by Luvnet-890** [comment]
Thank you.
