### ISSUE TITLE
Casting/Converting from a CustomFields.DateCustomField value

### ISSUE THREAD

**Issue by gregarican** [DavidRouyer/pipedrive-dotnet#76]
If I am iterating through Person records and see one of these, what's the most effective way to cast/convert the value to a C# DateTime object?

**Comment by gregarican** [comment]
Answered my own question...lol. It's been awhile since I've worked with this so was rusty. This appears to do the trick!

`var birthday = new DateCustomField(new DateTime());
                birthday = (DateCustomField)person.CustomFields[birthdayFieldKey];
                var birthdayVal = birthday.Value;
                `

**Comment by DavidRouyer** [comment]
I have an utility method to convert a `DateCustomField` for example to a `DateTime?`
```csharp
        public static DateTime? Date(ICustomField customField)
        {
            DateTime? value = null;
            if (customField != null)
            {
                value = ((DateCustomField)customField).Value;
            }

            return value;
        }
```

It can be improved with a try/catch if the conversion fails
