### ISSUE TITLE
Add Subscriptions

### ISSUE THREAD

**Issue by 756gzdz5** [DavidRouyer/pipedrive-dotnet#82]
As far as I understand, the Subscriptions API isn't yet supported. That would be a great addition.

**Comment by DavidRouyer** [comment]
Hi! Thank you for your suggestion!

Can you tell me what are the most important endpoints you need in order to prioritize them? You can see the list of endpoints here : https://developers.pipedrive.com/docs/api/v1/Subscriptions#getSubscription

**Comment by 756gzdz5** [comment]
Hi, thank you for your reply!

For me, the most important aspects are creating and canceling a recurring subscription.

**Comment by DavidRouyer** [comment]
Hi there,

I've started working on it but I struggle with the Pipedrive API. All of the Subscriptions endpoints are returning a 404 so I can't test them :/ 
You can follow my work here: https://github.com/DavidRouyer/pipedrive-dotnet/pull/83

**Comment by 756gzdz5** [comment]
At least at the moment, I can retrieve subscriptions using Postman.

**Comment by DavidRouyer** [comment]
I'm using a sandbox account, maybe it works in production

**Comment by DavidRouyer** [comment]
Hi, can you take a look at the new release? https://github.com/DavidRouyer/pipedrive-dotnet/releases/tag/v0.5.12

**Comment by 756gzdz5** [comment]
Thank you for your update!
However, I just updated to 0.5.12. using npm and I don't find the subscriptions in PipedriveClient. I am doing something wrong?

**Comment by DavidRouyer** [comment]
On nuget you mean? Try `0.5.13`, `0.5.12` hasn't been packaged correctly

**Comment by 756gzdz5** [comment]
I'm sorry I only got to play with it today.
I'm failing to create a new subscription due to the following error, although I'm not even setting payments:
`HttpResponseBodySafe = "{\"success\":false,\"statusCode\":10009,\"error\":\"HTTP request is not valid\",\"error_info\":\"'body.payments' must be an array\",\"data\":null}"`

**Comment by DavidRouyer** [comment]
As the error says you have to pass an array of payments (try to pass an empty array). If it does not work, it's an issue on their side because it is not mandatory for a recurring subscription https://developers.pipedrive.com/docs/api/v1/Subscriptions#addRecurringSubscription

**Comment by 756gzdz5** [comment]
If I actually pass an empty array for that optional parameter, the error changes to `'body.payments' must contain at least 1 items\`. 
Also, you don't seem to have to pass that parameter in SubscriptionsClientTests.cs neither.

**Comment by DavidRouyer** [comment]
You don't need to pass a payments array anymore, I fixed it in `0.5.14`.
You can find an example here: https://github.com/DavidRouyer/pipedrive-dotnet/blob/61c286d186838a9cc9fa5db0eb5a933d2b044d0a/src/Pipedrive.net.Tests.Integration/Clients/SubscriptionsClientTests.cs#L52-L79

**Comment by 756gzdz5** [comment]
Thank you so much. It's working perfectly fine now.

**Comment by 756gzdz5** [comment]
Are you also planning to add the option to update subscriptions?

**Comment by DavidRouyer** [comment]
Of course, I have two remaining endpoints to implement

**Comment by DavidRouyer** [comment]
You can try `0.5.16` to edit subscriptions
