### ISSUE TITLE
Consuming Organization with Custom Fields

### ISSUE THREAD

**Issue by mmarquesbr** [DavidRouyer/pipedrive-dotnet#86]
Hi David!

The organization's custom fields values are returning empty and I can't figure out what is wrong with my code:

Organization from Pipedrive screen:
<img width="483" alt="Organization" src="https://user-images.githubusercontent.com/2555085/123288420-f05a9680-d4e5-11eb-86ba-6a4c25b344ae.png">

Organization from pipedrive-dotnet:
`{
  "custom_fields": {
    "d69d827d846356c40445411bd60d0244edf936f9": {},
    "ee03456d7963cbfff17ec7cd3360d669850a0a57": null,
    "b558fa523aeec8426093cec7adfdf1d20c1c55f8": {},
    "25194dc3627fee0d24d0c5a2d0b3476109481cd3": null,
    "b11cc4c9548de93ca006d53be75c941228efb311": null,
    "283fcf884a0ab6dab5d2b1164116dd84df0801ab": null,
    "ce786d20752af44410c3529a348505ce80518fa9": null,
    "2f227d24d050312aeb20af373cb91a9f98723867": null,
    "d80787a1ed7af1854f2afca531329768bfa5de7e": null,
    "bf90b7d12d092c4f5cd4fcf5dde11560adcf5335": null,
    "5c30f688dfe67340720f11ef30974683ba9d6ac4": null,
    "c7670d435ba305c4eb4b3d209d52c636cff28a19": null,
    "32156f3464fbd3d62cbeb20f84d4a220f330255c": null,
    "b0b4b8f01ba944c93db46b1708a183984cb5f6dc": null,
    "22f204d3ca74a5893ef5b1d880fc38dc0bef53d2": null,
    "247adc02f7b234ca39df890fa9551f49f848ebd1": {},
    "ec742597cbd8f4adee36b483ec8d19337bf8a749": null,
    "118289dd7ce576cd2c9f458d532675f05b322f24": null,
    "d77c2ca1272d9b35420a7168fbcf27d331f763aa": null,
    "0131d9620b7f45f4453a08f0b5b0cecaabde9b12": null,
    "2a9991503d5c70f879168090ce1719a58b2ad282": null
  },
  "id": 72660,
  "company_id": 2423203,
[...]
`
I need to retrieve all custom fields and I tried to consume just ["0131d9620b7f45f4453a08f0b5b0cecaabde9b12"] with no success too. I thought that all fields would return filled automatically in the organization request. - Could you please help me out?

Thank you for sharing this library. - Great work!

**Comment by DavidRouyer** [comment]
Hi, are you sure that you are fetching the right entity? Can you try to make a HTTP request to see if the fields are there? 
`GET https://[your-domain].pipedrive.com/v1/deals/[your_deal_id]?api_token=[your_token]`

Can you show me your code?

I've improved my integration tests https://github.com/DavidRouyer/pipedrive-dotnet/commit/80c8134fec0764d126ab40978a35077df20233e8 to make sure that the custom fields are returned

**Comment by mmarquesbr** [comment]
Hi David,

I was fetching the right endpoint but in the wrong way. 

I've checked your integration tests and that solved my doubts.

Thank you very much for your time.

**Comment by DavidRouyer** [comment]
No problem! Feel free to open issues if you have any problem/question
